### ISSUE TITLE
ARM64/Window/MacOS wheels not built for 1.4.0

### ISSUE THREAD

**Issue by sema-3** [OHF-Voice/piper1-gpl#171]
In ./workflows/publish.yml all target OS besides ubuntu-latest are deactivated.

line 16:  `os: [ubuntu-latest] #, ubuntu-24.04-arm, windows-latest, macos-13, macos-lat`

I noticed this when installing on a raspberry pi 5 via [wyoming-piper](https://github.com/rhasspy/wyoming-piper) 
As a workaround I built piper-tts manually on the target and that worked, [build instructions](https://github.com/OHF-Voice/piper1-gpl/blob/main/docs/BUILDING.md)

**Comment by StevenKRT** [comment]
I can reproduce this on a Raspberry Pi (ARM64) with wyoming-piper 2.2.1.

Behavior:

The container starts normally, downloads the voice (de_DE-thorsten-medium) and reports Ready

On the first synthesize request it fails with
ImportError: cannot import name 'espeakbridge' from 'piper'

This is followed by wave.Error: # channels not specified as a secondary error

Notes:

This happens both with the Home Assistant Piper add-on and with the standalone rhasspy/wyoming-piper Docker container

The issue occurs at runtime during synthesis, not during startup or model download

**Comment by sema-3** [comment]
Confirmation that it's working with v 1.4.1.
Thank you!
